# Numpy Versus Pandas

## Numpy 

- Definition
    Numpy means and stands for Numerical Python 

- Usage
    For an array or matrix based calculation and analysis for data

- Why
    We can easily use for complex calculation for array and matrix structure data without looping as if it's a scalar entity

In [11]:
import numpy as np

# generage integer ranged from 0 to 8 for 9 digits and shape it 3 by 3 matrix structure
arr1 = np.arange(9).reshape(3, 3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
arr2 = np.arange(9, 18).reshape(3, 3)
arr2

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [13]:
# calculate two matrix that are in same shape 
# Addition
arr3 = arr1 + arr2
arr3

array([[ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])

In [14]:
arr4 = arr1 * arr2
arr4

array([[  0,  10,  22],
       [ 36,  52,  70],
       [ 90, 112, 136]])

In [15]:
arr5 = arr1 / arr2
arr5

array([[0.        , 0.1       , 0.18181818],
       [0.25      , 0.30769231, 0.35714286],
       [0.4       , 0.4375    , 0.47058824]])

In [16]:
arrScalarMultiplication = arr1 * 10
arrScalarMultiplication

array([[ 0, 10, 20],
       [30, 40, 50],
       [60, 70, 80]])

In [17]:
arrScalarAddition = arr2 + 100
arrScalarAddition

array([[109, 110, 111],
       [112, 113, 114],
       [115, 116, 117]])

## Pandas 

- Definition
    Pandas stands for Python for Data Analysis

- Usage
    Like Numpy it processes data without loop 

# Difference Numpy versus Pandas

Pandas uses the data structures of datarames and series for tabular format with various data types,

while Numpy is best suited for the collection of the same type of data

In [ ]:
# Difference

