# Numpy

### Lists Recap
    - Powerful with various functions and methods
    - Collection of values
    - Hold different types
    - Change, add, remove


### Data Science Perspective
    - Mathematical Operations required over collections
    - speed - faster


### NumPy
    - Numeric Python
    - Alternative to Python list: NumPy Array
    - Calculations over entire arrays
    - Easy and Fast
    - intallation


In [4]:
import numpy as np

np.array(np.arange(9).reshape(3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
from numpy import array as arr

# but recommended to import whole numpy package and use it clearly


arr(np.arange(9,18).reshape(3, 3))


array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [22]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]

list3 = list1 + list2
print(list3)


arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = arr1 + arr2
print(arr3)


[1, 2, 3, 4, 5, 6]
[5 7 9]


### NumPy Subsetting

In [23]:
res = arr3 > 5
print(res) # return boolean

[False  True  True]


In [24]:
arr3[res] # subset the array with condition that returns True Or False

array([7, 9])

In [25]:
res1 = np.array([True, 1, 2]) + np.array([3, 4, False])
print(res1)

res2 = np.array([4, 3, 0]) + np.array([0, 2, 2])
print(res2)

[4 5 2]
[4 5 2]


In [27]:
print(res1[1])
print(res2[:2])

5
[4 5]


## N-D Arrays

In [28]:
np_2d = np.array([[1, 2, 3, 4, 5], 
[0, 1, 2, 3, 4]])

np_2d

array([[1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4]])

In [29]:
np_2d.shape # structure attributes


(2, 5)

In [31]:
print(np_2d[0][2])
print(np_2d[0, 2])
print(np_2d[:, 1:3])
print(np_2d[1, :])

3
3
[[2 3]
 [1 2]]
[0 1 2 3 4]


### Basic Statistics with Numpy

In [38]:
# basic statistics

print(np_2d)

# sort
print(np.sort(np_2d[:, 1]))

# sum
print(np.sum(np_2d[: 1]))

# mean
print(np.mean(np_2d[:, 1]))

# median
print(np.median(np_2d[:, 1]))

# correlation
print(np.corrcoef(np_2d[:, 0], np_2d[:, 1]))




[[1 2 3 4 5]
 [0 1 2 3 4]]
[1 2]
15
1.5
1.5
[[1. 1.]
 [1. 1.]]


### Generating Data

In [42]:
# random method 
np.random.normal()
# distribution mean
# distribution standard deviatin
# number of samples

height = np.round(np.random.normal(1.75, 0.20, 5000), 2)
weight = np.round(np.random.normal(60.32, 15, 5000), 2)
np_city = np.column_stack((height, weight))

print(height)
print(weight)
print(np_city)

[2.01 1.87 1.58 ... 2.12 2.09 1.75]
[64.54 84.72 73.2  ... 34.81 79.92 55.84]
[[ 2.01 64.54]
 [ 1.87 84.72]
 [ 1.58 73.2 ]
 ...
 [ 2.12 34.81]
 [ 2.09 79.92]
 [ 1.75 55.84]]
